with-expecter: true
boilerplate-file: ".mockery_boilerplate_text.txt"
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
  github.com/mbakhodurov/examples/week_2/unit_tests/6_unit_test_in_clean_arch/internal/service:
    config:
      include-regex: ".*Service"

  github.com/mbakhodurov/examples/week_2/unit_tests/6_unit_test_in_clean_arch/internal/repository:
    config:
      include-regex: ".*Repository"
