// Code generated for mbakhodurov service
// © mbakhodurov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mbakhodurov/examples/week_2/unit_tests/6_unit_test_in_clean_arch/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UFOService is an autogenerated mock type for the UFOService type
type UFOService struct {
	mock.Mock
}

type UFOService_Expecter struct {
	mock *mock.Mock
}

func (_m *UFOService) EXPECT() *UFOService_Expecter {
	return &UFOService_Expecter{mock: &_m.Mock}
}

// CreateSighting provides a mock function with given fields: ctx, info
func (_m *UFOService) CreateSighting(ctx context.Context, info model.SightingInfo) (string, error) {
	ret := _m.Called(ctx, info)

	if len(ret) == 0 {
		panic("no return value specified for CreateSighting")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) (string, error)); ok {
		return rf(ctx, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) string); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SightingInfo) error); ok {
		r1 = rf(ctx, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFOService_CreateSighting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSighting'
type UFOService_CreateSighting_Call struct {
	*mock.Call
}

// CreateSighting is a helper method to define mock.On call
//   - ctx context.Context
//   - info model.SightingInfo
func (_e *UFOService_Expecter) CreateSighting(ctx interface{}, info interface{}) *UFOService_CreateSighting_Call {
	return &UFOService_CreateSighting_Call{Call: _e.mock.On("CreateSighting", ctx, info)}
}

func (_c *UFOService_CreateSighting_Call) Run(run func(ctx context.Context, info model.SightingInfo)) *UFOService_CreateSighting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SightingInfo))
	})
	return _c
}

func (_c *UFOService_CreateSighting_Call) Return(_a0 string, _a1 error) *UFOService_CreateSighting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFOService_CreateSighting_Call) RunAndReturn(run func(context.Context, model.SightingInfo) (string, error)) *UFOService_CreateSighting_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSight provides a mock function with given fields: ctx, uuids
func (_m *UFOService) DeleteSight(ctx context.Context, uuids string) error {
	ret := _m.Called(ctx, uuids)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFOService_DeleteSight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSight'
type UFOService_DeleteSight_Call struct {
	*mock.Call
}

// DeleteSight is a helper method to define mock.On call
//   - ctx context.Context
//   - uuids string
func (_e *UFOService_Expecter) DeleteSight(ctx interface{}, uuids interface{}) *UFOService_DeleteSight_Call {
	return &UFOService_DeleteSight_Call{Call: _e.mock.On("DeleteSight", ctx, uuids)}
}

func (_c *UFOService_DeleteSight_Call) Run(run func(ctx context.Context, uuids string)) *UFOService_DeleteSight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFOService_DeleteSight_Call) Return(_a0 error) *UFOService_DeleteSight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFOService_DeleteSight_Call) RunAndReturn(run func(context.Context, string) error) *UFOService_DeleteSight_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, uuid
func (_m *UFOService) Get(ctx context.Context, uuid string) (model.Sighting, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Sighting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Sighting, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Sighting); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Sighting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFOService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UFOService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFOService_Expecter) Get(ctx interface{}, uuid interface{}) *UFOService_Get_Call {
	return &UFOService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *UFOService_Get_Call) Run(run func(ctx context.Context, uuid string)) *UFOService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFOService_Get_Call) Return(_a0 model.Sighting, _a1 error) *UFOService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFOService_Get_Call) RunAndReturn(run func(context.Context, string) (model.Sighting, error)) *UFOService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *UFOService) GetAll(ctx context.Context) ([]model.Sighting, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Sighting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Sighting, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Sighting); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Sighting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFOService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type UFOService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UFOService_Expecter) GetAll(ctx interface{}) *UFOService_GetAll_Call {
	return &UFOService_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *UFOService_GetAll_Call) Run(run func(ctx context.Context)) *UFOService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UFOService_GetAll_Call) Return(_a0 []model.Sighting, _a1 error) *UFOService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFOService_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Sighting, error)) *UFOService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSight provides a mock function with given fields: ctx, uuid, info
func (_m *UFOService) UpdateSight(ctx context.Context, uuid string, info model.SightingUpdateInfo) error {
	ret := _m.Called(ctx, uuid, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSight")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SightingUpdateInfo) error); ok {
		r0 = rf(ctx, uuid, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFOService_UpdateSight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSight'
type UFOService_UpdateSight_Call struct {
	*mock.Call
}

// UpdateSight is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - info model.SightingUpdateInfo
func (_e *UFOService_Expecter) UpdateSight(ctx interface{}, uuid interface{}, info interface{}) *UFOService_UpdateSight_Call {
	return &UFOService_UpdateSight_Call{Call: _e.mock.On("UpdateSight", ctx, uuid, info)}
}

func (_c *UFOService_UpdateSight_Call) Run(run func(ctx context.Context, uuid string, info model.SightingUpdateInfo)) *UFOService_UpdateSight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SightingUpdateInfo))
	})
	return _c
}

func (_c *UFOService_UpdateSight_Call) Return(_a0 error) *UFOService_UpdateSight_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFOService_UpdateSight_Call) RunAndReturn(run func(context.Context, string, model.SightingUpdateInfo) error) *UFOService_UpdateSight_Call {
	_c.Call.Return(run)
	return _c
}

// NewUFOService creates a new instance of UFOService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUFOService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UFOService {
	mock := &UFOService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
