// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: classification/v1/classification.proto

package classification_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ClassifyObjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClassifyObjectRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifyObjectRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifyObjectRequestMultiError, or nil if none found.
func (m *ClassifyObjectRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifyObjectRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Description

	// no validation rules for Color

	// no validation rules for DurationSeconds

	if len(errors) > 0 {
		return ClassifyObjectRequestMultiError(errors)
	}

	return nil
}

// ClassifyObjectRequestMultiError is an error wrapping multiple validation
// errors returned by ClassifyObjectRequest.ValidateAll() if the designated
// constraints aren't met.
type ClassifyObjectRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifyObjectRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifyObjectRequestMultiError) AllErrors() []error { return m }

// ClassifyObjectRequestValidationError is the validation error returned by
// ClassifyObjectRequest.Validate if the designated constraints aren't met.
type ClassifyObjectRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifyObjectRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifyObjectRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifyObjectRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifyObjectRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifyObjectRequestValidationError) ErrorName() string {
	return "ClassifyObjectRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifyObjectRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifyObjectRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifyObjectRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifyObjectRequestValidationError{}

// Validate checks the field values on ClassifyObjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ClassifyObjectResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ClassifyObjectResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ClassifyObjectResponseMultiError, or nil if none found.
func (m *ClassifyObjectResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClassifyObjectResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ObjectType

	// no validation rules for Confidence

	// no validation rules for Explanation

	if len(errors) > 0 {
		return ClassifyObjectResponseMultiError(errors)
	}

	return nil
}

// ClassifyObjectResponseMultiError is an error wrapping multiple validation
// errors returned by ClassifyObjectResponse.ValidateAll() if the designated
// constraints aren't met.
type ClassifyObjectResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClassifyObjectResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClassifyObjectResponseMultiError) AllErrors() []error { return m }

// ClassifyObjectResponseValidationError is the validation error returned by
// ClassifyObjectResponse.Validate if the designated constraints aren't met.
type ClassifyObjectResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClassifyObjectResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClassifyObjectResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClassifyObjectResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClassifyObjectResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClassifyObjectResponseValidationError) ErrorName() string {
	return "ClassifyObjectResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ClassifyObjectResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClassifyObjectResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClassifyObjectResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClassifyObjectResponseValidationError{}
