// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: events/v1/ufo.proto

package events_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UFORecorded with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UFORecorded) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UFORecorded with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UFORecordedMultiError, or
// nil if none found.
func (m *UFORecorded) ValidateAll() error {
	return m.validate(true)
}

func (m *UFORecorded) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if all {
		switch v := interface{}(m.GetObservedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UFORecordedValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UFORecordedValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObservedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UFORecordedValidationError{
				field:  "ObservedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Location

	// no validation rules for Description

	if len(errors) > 0 {
		return UFORecordedMultiError(errors)
	}

	return nil
}

// UFORecordedMultiError is an error wrapping multiple validation errors
// returned by UFORecorded.ValidateAll() if the designated constraints aren't met.
type UFORecordedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UFORecordedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UFORecordedMultiError) AllErrors() []error { return m }

// UFORecordedValidationError is the validation error returned by
// UFORecorded.Validate if the designated constraints aren't met.
type UFORecordedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UFORecordedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UFORecordedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UFORecordedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UFORecordedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UFORecordedValidationError) ErrorName() string { return "UFORecordedValidationError" }

// Error satisfies the builtin error interface
func (e UFORecordedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUFORecorded.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UFORecordedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UFORecordedValidationError{}
