version: '3'
vars:
  MOCKERY_VERSION: 'v2.53.3'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  MOCKERY: "{{.BIN_DIR}}/mockery"

tasks:
  mockery:install:
    desc: "Устанавливает mockery в ./bin"
    cmds:
      - |
        [ -f {{.MOCKERY}} ] || {
          echo '📦 Installing mockery...'
          GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v2@{{.MOCKERY_VERSION}}
        }
    status:
      - test -x {{.MOCKERY}}