// Code generated for mbakhodurov service
// © mbakhodurov 2025.

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mbakhodurov/examples/week_2/unit_tests/6_unit_test_in_clean_arch/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UFORepository is an autogenerated mock type for the UFORepository type
type UFORepository struct {
	mock.Mock
}

type UFORepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UFORepository) EXPECT() *UFORepository_Expecter {
	return &UFORepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, sighting
func (_m *UFORepository) Create(ctx context.Context, sighting model.SightingInfo) (string, error) {
	ret := _m.Called(ctx, sighting)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) (string, error)); ok {
		return rf(ctx, sighting)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.SightingInfo) string); ok {
		r0 = rf(ctx, sighting)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.SightingInfo) error); ok {
		r1 = rf(ctx, sighting)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFORepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UFORepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - sighting model.SightingInfo
func (_e *UFORepository_Expecter) Create(ctx interface{}, sighting interface{}) *UFORepository_Create_Call {
	return &UFORepository_Create_Call{Call: _e.mock.On("Create", ctx, sighting)}
}

func (_c *UFORepository_Create_Call) Run(run func(ctx context.Context, sighting model.SightingInfo)) *UFORepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SightingInfo))
	})
	return _c
}

func (_c *UFORepository_Create_Call) Return(_a0 string, _a1 error) *UFORepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFORepository_Create_Call) RunAndReturn(run func(context.Context, model.SightingInfo) (string, error)) *UFORepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUUID provides a mock function with given fields: ctx, uuid
func (_m *UFORepository) DeleteByUUID(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFORepository_DeleteByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUUID'
type UFORepository_DeleteByUUID_Call struct {
	*mock.Call
}

// DeleteByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFORepository_Expecter) DeleteByUUID(ctx interface{}, uuid interface{}) *UFORepository_DeleteByUUID_Call {
	return &UFORepository_DeleteByUUID_Call{Call: _e.mock.On("DeleteByUUID", ctx, uuid)}
}

func (_c *UFORepository_DeleteByUUID_Call) Run(run func(ctx context.Context, uuid string)) *UFORepository_DeleteByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFORepository_DeleteByUUID_Call) Return(_a0 error) *UFORepository_DeleteByUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFORepository_DeleteByUUID_Call) RunAndReturn(run func(context.Context, string) error) *UFORepository_DeleteByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *UFORepository) GetAll(ctx context.Context) ([]model.Sighting, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Sighting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Sighting, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Sighting); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Sighting)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFORepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type UFORepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UFORepository_Expecter) GetAll(ctx interface{}) *UFORepository_GetAll_Call {
	return &UFORepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *UFORepository_GetAll_Call) Run(run func(ctx context.Context)) *UFORepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UFORepository_GetAll_Call) Return(_a0 []model.Sighting, _a1 error) *UFORepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFORepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]model.Sighting, error)) *UFORepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUUID provides a mock function with given fields: ctx, uuid
func (_m *UFORepository) GetByUUID(ctx context.Context, uuid string) (model.Sighting, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetByUUID")
	}

	var r0 model.Sighting
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.Sighting, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Sighting); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Sighting)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UFORepository_GetByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUUID'
type UFORepository_GetByUUID_Call struct {
	*mock.Call
}

// GetByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *UFORepository_Expecter) GetByUUID(ctx interface{}, uuid interface{}) *UFORepository_GetByUUID_Call {
	return &UFORepository_GetByUUID_Call{Call: _e.mock.On("GetByUUID", ctx, uuid)}
}

func (_c *UFORepository_GetByUUID_Call) Run(run func(ctx context.Context, uuid string)) *UFORepository_GetByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UFORepository_GetByUUID_Call) Return(_a0 model.Sighting, _a1 error) *UFORepository_GetByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UFORepository_GetByUUID_Call) RunAndReturn(run func(context.Context, string) (model.Sighting, error)) *UFORepository_GetByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateByUUID provides a mock function with given fields: ctx, uuid, updateInfo
func (_m *UFORepository) UpdateByUUID(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo) error {
	ret := _m.Called(ctx, uuid, updateInfo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByUUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, model.SightingUpdateInfo) error); ok {
		r0 = rf(ctx, uuid, updateInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UFORepository_UpdateByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateByUUID'
type UFORepository_UpdateByUUID_Call struct {
	*mock.Call
}

// UpdateByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
//   - updateInfo model.SightingUpdateInfo
func (_e *UFORepository_Expecter) UpdateByUUID(ctx interface{}, uuid interface{}, updateInfo interface{}) *UFORepository_UpdateByUUID_Call {
	return &UFORepository_UpdateByUUID_Call{Call: _e.mock.On("UpdateByUUID", ctx, uuid, updateInfo)}
}

func (_c *UFORepository_UpdateByUUID_Call) Run(run func(ctx context.Context, uuid string, updateInfo model.SightingUpdateInfo)) *UFORepository_UpdateByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(model.SightingUpdateInfo))
	})
	return _c
}

func (_c *UFORepository_UpdateByUUID_Call) Return(_a0 error) *UFORepository_UpdateByUUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UFORepository_UpdateByUUID_Call) RunAndReturn(run func(context.Context, string, model.SightingUpdateInfo) error) *UFORepository_UpdateByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// NewUFORepository creates a new instance of UFORepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUFORepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UFORepository {
	mock := &UFORepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
