// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: analysis/v1/analysis.proto

package analysis_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AnalyzeSightingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzeSightingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzeSightingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AnalyzeSightingRequestMultiError, or nil if none found.
func (m *AnalyzeSightingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzeSightingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uuid

	if len(errors) > 0 {
		return AnalyzeSightingRequestMultiError(errors)
	}

	return nil
}

// AnalyzeSightingRequestMultiError is an error wrapping multiple validation
// errors returned by AnalyzeSightingRequest.ValidateAll() if the designated
// constraints aren't met.
type AnalyzeSightingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzeSightingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzeSightingRequestMultiError) AllErrors() []error { return m }

// AnalyzeSightingRequestValidationError is the validation error returned by
// AnalyzeSightingRequest.Validate if the designated constraints aren't met.
type AnalyzeSightingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzeSightingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzeSightingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzeSightingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzeSightingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzeSightingRequestValidationError) ErrorName() string {
	return "AnalyzeSightingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzeSightingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzeSightingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzeSightingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzeSightingRequestValidationError{}

// Validate checks the field values on AnalyzeSightingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AnalyzeSightingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AnalyzeSightingResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AnalyzeSightingResponseMultiError, or nil if none found.
func (m *AnalyzeSightingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *AnalyzeSightingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AnalysisResult

	// no validation rules for Classification

	// no validation rules for ConfidenceScore

	if len(errors) > 0 {
		return AnalyzeSightingResponseMultiError(errors)
	}

	return nil
}

// AnalyzeSightingResponseMultiError is an error wrapping multiple validation
// errors returned by AnalyzeSightingResponse.ValidateAll() if the designated
// constraints aren't met.
type AnalyzeSightingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AnalyzeSightingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AnalyzeSightingResponseMultiError) AllErrors() []error { return m }

// AnalyzeSightingResponseValidationError is the validation error returned by
// AnalyzeSightingResponse.Validate if the designated constraints aren't met.
type AnalyzeSightingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AnalyzeSightingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AnalyzeSightingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AnalyzeSightingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AnalyzeSightingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AnalyzeSightingResponseValidationError) ErrorName() string {
	return "AnalyzeSightingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e AnalyzeSightingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAnalyzeSightingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AnalyzeSightingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AnalyzeSightingResponseValidationError{}
